import type { Metadata } from "next";
import { SubPage } from "../_components/SiteChrome";

export const metadata: Metadata = {
  title: "คลังความรู้ | LearnerLens",
  description: "ความรู้สำหรับครูเรื่องจิตวิทยาการเรียนรู้ พัฒนาการ UDL การสอนที่ตอบสนองความแตกต่าง และการศึกษาแบบเรียนรวม",
  alternates: { canonical: "/knowledge" },
  openGraph: { title: "คลังความรู้ | LearnerLens", description: "ทฤษฎี งานวิจัย ตัวอย่าง Checklist และคำถามสะท้อนคิดสำหรับครู", url: "/knowledge", images: [] },
  twitter: { title: "คลังความรู้ | LearnerLens", description: "ทฤษฎี งานวิจัยและตัวอย่างที่นำไปใช้ได้จริง", images: [] },
};

const topics = [
  {id:"learning-psychology",title:"จิตวิทยาการเรียนรู้",theory:"Piaget · Vygotsky · Bruner · Bandura",summary:"การเรียนรู้เกิดจากการเชื่อมโยงประสบการณ์เดิม ปฏิสัมพันธ์ทางสังคม การพยุงที่พอดี และความเชื่อว่าตนเองทำได้",example:"ก่อนเริ่มเรื่องเศษส่วน ให้ผู้เรียนอธิบายความเข้าใจเดิมด้วยภาพ จากนั้นจับคู่คิดและใช้คำถามนำทีละขั้น",check:["ตรวจความรู้เดิมก่อนสอน","จัดการพยุงที่ค่อย ๆ ลดลง","ให้ข้อมูลย้อนกลับที่ชี้วิธีพัฒนา"],reflect:"ส่วนใดของงานที่ผู้เรียนทำได้เอง และส่วนใดที่ทำได้เมื่อมีคนช่วย?"},
  {id:"child-development",title:"พัฒนาการเด็ก",theory:"Developmental perspective",summary:"พัฒนาการด้านกาย สติปัญญา ภาษา อารมณ์ และสังคมเชื่อมโยงกัน แต่มีจังหวะและเส้นทางที่ต่างกันในแต่ละคน",example:"ลดภาระการเขียนยาวในกิจกรรมที่ต้องการวัดการคิด และให้ตอบด้วยการเล่า แผนภาพ หรืออุปกรณ์แทนได้",check:["ดูความพร้อมมากกว่าอายุเพียงอย่างเดียว","เก็บข้อมูลหลายบริบท","ปรึกษาผู้เชี่ยวชาญเมื่อจำเป็น"],reflect:"ความยากที่เห็นมาจากเป้าหมายการเรียนรู้ หรือจากรูปแบบงานที่กำหนด?"},
  {id:"individual-differences",title:"ความแตกต่างระหว่างบุคคล",theory:"Readiness · Interest · Learner profile",summary:"ความพร้อม ความสนใจ ประสบการณ์ ภาษา จุดแข็ง และบริบทชีวิตทำให้ผู้เรียนตอบสนองต่อบทเรียนเดียวกันต่างกัน",example:"ใช้บัตรทางเลือก 3 ระดับการพยุง โดยทุกคนยังทำงานสู่เป้าหมายและเกณฑ์คุณภาพเดียวกัน",check:["ระบุเป้าหมายแกนกลาง","แยกอุปสรรคออกจากตัวผู้เรียน","วางทางเลือกที่ไม่ลดความคาดหวัง"],reflect:"เรากำลังปรับเส้นทาง หรือกำลังลดเป้าหมายโดยไม่ตั้งใจ?"},
  {id:"multiple-intelligences",title:"ความฉลาดหลากหลาย",theory:"Howard Gardner",summary:"ใช้เป็นเลนส์มองศักยภาพที่หลากหลาย ไม่ใช่แบบทดสอบเพื่อติดป้ายหรือจำกัดวิธีเรียนของเด็ก",example:"ให้ผู้เรียนสำรวจประเด็นเดียวผ่านภาษา เหตุผล พื้นที่ ดนตรี การเคลื่อนไหว ธรรมชาติ หรือการทำงานกับผู้อื่น",check:["เปิดหลายช่องทางสู่เป้าหมาย","ไม่สรุปว่าผู้เรียนมีความฉลาดเพียงด้านเดียว","ประเมินตามเป้าหมาย ไม่ใช่ความสวยของสื่อ"],reflect:"ทางเลือกนี้เปิดให้เห็นความคิด หรือเพียงเปลี่ยนรูปแบบชิ้นงาน?"},
  {id:"learning-preferences",title:"ความชอบในการเรียนรู้",theory:"Evidence-informed caution",summary:"ผู้เรียนอาจมีความชอบที่เปลี่ยนตามงานและบริบท แต่หลักฐานไม่สนับสนุนการจับคู่การสอนกับ “Learning Style” แบบตายตัว",example:"ใช้ภาพเมื่อเนื้อหาต้องการความสัมพันธ์เชิงพื้นที่ ใช้เสียงเมื่อจำเป็นต่อการออกเสียง และให้ทุกคนฝึกหลายกลยุทธ์",check:["เลือกสื่อตามธรรมชาติของเนื้อหา","หลีกเลี่ยงป้าย visual/auditory/kinesthetic","สอนให้ผู้เรียนเลือกกลยุทธ์อย่างมีเหตุผล"],reflect:"สื่อนี้ช่วยให้เข้าใจเนื้อหาเพราะอะไร ไม่ใช่เพราะป้ายประเภทใด?"},
  {id:"motivation",title:"แรงจูงใจและ Growth Mindset",theory:"Bandura · Self-efficacy",summary:"แรงจูงใจเติบโตเมื่อผู้เรียนเห็นความหมาย มีความเป็นเจ้าของ ได้รับความท้าทายที่พอดี และมองเห็นความก้าวหน้าของตน",example:"ให้ผู้เรียนเลือกโจทย์จากบริบทที่สนใจ ตั้งเป้าหมายสั้น และสะท้อนกลยุทธ์ที่ช่วยให้ก้าวหน้า",check:["ให้ทางเลือกที่มีความหมาย","ชี้ความก้าวหน้าจากหลักฐาน","ชมกระบวนการและกลยุทธ์อย่างเฉพาะเจาะจง"],reflect:"ผู้เรียนเห็นหรือยังว่าเหตุใดงานนี้จึงสำคัญต่อเขา?"},
  {id:"executive-functions",title:"Executive Functions",theory:"Working memory · Inhibition · Flexibility",summary:"การเริ่มงาน จดจำคำสั่ง วางแผน ยับยั้ง และเปลี่ยนกลยุทธ์เป็นทักษะที่พัฒนาได้ และอาจถูกกดทับเมื่อมีความเครียด",example:"แสดงขั้นตอนเป็นภาพ ให้เริ่มจากงาน 3 นาที ใช้ตัวจับเวลา และมีจุดหยุดทบทวนกลางงาน",check:["ลดคำสั่งหลายขั้นในครั้งเดียว","ทำก้าวแรกให้มองเห็น","ให้เครื่องมือจัดระบบโดยไม่ลงโทษ"],reflect:"งานนี้ต้องใช้ทักษะกำกับตนเองซ่อนอยู่กี่อย่าง?"},
  {id:"inclusive-education",title:"Inclusive Education",theory:"UNESCO · Equity and inclusion",summary:"การเรียนรวมไม่ได้หมายถึงการอยู่ในห้องเดียวกันเท่านั้น แต่หมายถึงการมีส่วนร่วม ได้รับการยอมรับ และก้าวหน้าอย่างมีความหมาย",example:"สำรวจว่าใครไม่ได้พูด ไม่ได้เลือก หรือไม่ถูกมองเห็น แล้วปรับกติกาการมีส่วนร่วมให้ทุกคนมีช่องทาง",check:["ทุกคนเข้าถึงพื้นที่และข้อมูลได้","ตัวอย่างสะท้อนอัตลักษณ์ที่หลากหลาย","ผู้เรียนมีเสียงในการตัดสินใจ"],reflect:"ใครยังไม่ได้มีส่วนร่วม และอุปสรรคอยู่ตรงไหนของระบบ?"},
  {id:"udl",title:"Universal Design for Learning",theory:"CAST UDL Guidelines 3.0",summary:"ออกแบบทางเลือกด้านการมีส่วนร่วม การรับข้อมูล และการลงมือหรือแสดงออกตั้งแต่ต้น เพื่อพัฒนา learner agency",example:"เป้าหมายคืออธิบายวัฏจักรน้ำ ผู้เรียนเลือกรับข้อมูลจากข้อความ ภาพเคลื่อนไหว หรือแบบจำลอง และเลือกอธิบายด้วยภาพ เสียง หรือข้อความ",check:["แยกเป้าหมายออกจากวิธีทำ","มีหลายวิธีเข้าถึงสาระสำคัญ","ใช้เกณฑ์คุณภาพเดียวกัน"],reflect:"อุปสรรคนี้เกิดจากผู้เรียน หรือจากการออกแบบที่มีทางเดียว?"},
  {id:"differentiation",title:"Differentiated Instruction",theory:"Carol Ann Tomlinson",summary:"ปรับเนื้อหา กระบวนการ ชิ้นงาน และสภาพแวดล้อมตามความพร้อม ความสนใจ และโปรไฟล์ โดยอาศัยการประเมินต่อเนื่อง",example:"ใช้ exit ticket แบ่งการพยุงชั่วคราว: กลุ่มทบทวนด้วยตัวอย่าง กลุ่มฝึกอิสระ และกลุ่มประยุกต์โจทย์ใหม่",check:["ใช้ข้อมูลล่าสุดจัดกลุ่ม","กลุ่มยืดหยุ่นและเปลี่ยนได้","ทุกกลุ่มทำงานที่มีคุณค่า"],reflect:"ข้อมูลอะไรบอกว่าควรปรับ และจะรู้ได้อย่างไรว่าการปรับช่วย?"},
  {id:"assessment-for-learning",title:"Assessment for Learning",theory:"Bloom · Gagné · Hattie",summary:"การประเมินเพื่อพัฒนาเก็บหลักฐานระหว่างเรียน ทำให้เป้าหมายชัด และให้ข้อมูลย้อนกลับที่ช่วยเลือกก้าวถัดไป",example:"จบคาบด้วยคำถามหนึ่งข้อ วิเคราะห์เหตุผลในคำตอบ แล้วปรับกิจกรรมเปิดคาบถัดไปตามความเข้าใจที่พบ",check:["ผู้เรียนรู้เกณฑ์ความสำเร็จ","หลักฐานสะท้อนการคิด ไม่ใช่แค่คำตอบ","Feedback ระบุก้าวถัดไปที่ทำได้"],reflect:"หลักฐานชิ้นนี้จะเปลี่ยนการสอนหรือการเรียนของเราต่อไปอย่างไร?"},
];

export default function KnowledgePage() {
  return <SubPage eyebrow="KNOWLEDGE HUB" title="ความรู้ที่ช่วยให้มองผู้เรียนได้ชัดขึ้น" description="เลือกหัวข้อ อ่านสรุป ดูตัวอย่างในห้องเรียน ใช้ Checklist และหยุดคิดด้วยคำถามสะท้อนผล"><section className="subpage-section" id="top"><nav className="topic-index" aria-label="สารบัญหัวข้อความรู้">{topics.map(t=><a key={t.id} href={`#${t.id}`}>{t.title}</a>)}</nav><div className="article-stack">{topics.map((topic,index)=><article className="knowledge-article" id={topic.id} key={topic.id}><div className="article-number">{String(index+1).padStart(2,"0")}</div><div><span className="case-tag">{topic.theory}</span><h2>{topic.title}</h2><div className="takeaway"><strong>สรุปสาระสำคัญ</strong><p>{topic.summary}</p></div><h3>ตัวอย่างในห้องเรียน</h3><p>{topic.example}</p><div className="article-columns"><div><h3>Checklist</h3><ul>{topic.check.map(item=><li key={item}>✓ {item}</li>)}</ul></div><div className="reflection"><h3>Reflection Question</h3><p>{topic.reflect}</p></div></div><a className="text-link" href="/downloads">ดาวน์โหลด Template ที่เกี่ยวข้อง <span>→</span></a></div></article>)}</div><aside className="source-panel"><h2>แหล่งอ้างอิงหลัก</h2><p>เนื้อหาแปลเป็นแนวปฏิบัติสำหรับครู โดยคงข้อควรระวังด้านหลักฐานและไม่ใช้กรอบทฤษฎีเพื่อติดป้ายผู้เรียน</p><div><a href="https://udlguidelines.cast.org/more/frequently-asked-questions/" target="_blank" rel="noreferrer">CAST UDL Guidelines 3.0 ↗</a><a href="https://www.unesco.org/en/articles/guide-ensuring-inclusion-and-equity-education-0" target="_blank" rel="noreferrer">UNESCO: Inclusion and Equity ↗</a><a href="https://www.oecd.org/en/data/tools/oecd-learning-compass-2030.html" target="_blank" rel="noreferrer">OECD Learning Compass 2030 ↗</a><a href="https://educationendowmentfoundation.org.uk/education-evidence/teaching-learning-toolkit/learning-styles" target="_blank" rel="noreferrer">EEF: Learning Styles Evidence ↗</a></div></aside></section></SubPage>;
}
