import type { Metadata } from "next";
import { SubPage } from "../_components/SiteChrome";

export const metadata: Metadata = {
  title: "เกี่ยวกับโครงการ | LearnerLens",
  description: "จุดประสงค์ แนวคิด และข้อมูลผู้จัดทำเว็บไซต์ LearnerLens",
  openGraph: { title: "เกี่ยวกับโครงการ | LearnerLens", description: "เหตุผลที่ LearnerLens ถูกสร้างขึ้นและข้อมูลผู้จัดทำ", images: [] },
  twitter: { title: "เกี่ยวกับโครงการ | LearnerLens", description: "เหตุผลที่ LearnerLens ถูกสร้างขึ้นและข้อมูลผู้จัดทำ", images: [] },
};

export default function AboutPage() {
  return <SubPage eyebrow="ABOUT LEARNERLENS" title="เข้าใจผู้เรียน เพื่อออกแบบโอกาสที่ดีกว่า" description="LearnerLens เป็นแพลตฟอร์มความรู้และเครื่องมือสำหรับครู ที่เชื่อว่าความแตกต่างไม่ใช่ปัญหาที่ต้องกำจัด แต่เป็นข้อมูลสำคัญสำหรับการออกแบบการเรียนรู้"><section className="subpage-section about-grid" id="top"><article className="about-lead"><span className="section-kicker left">จุดประสงค์การจัดทำเว็บไซต์</span><h2>ทำให้ความรู้เรื่องผู้เรียน นำไปใช้ได้จริงในห้องเรียน</h2><p>เว็บไซต์นี้จัดทำขึ้นเพื่อช่วยให้ครูและผู้เกี่ยวข้องกับการศึกษาเข้าใจผู้เรียนเป็นรายบุคคลอย่างรอบด้าน มองเห็นทั้งจุดแข็ง ความสนใจ ความพร้อม พัฒนาการ อารมณ์ แรงจูงใจ และบริบทที่มีผลต่อการเรียนรู้</p><p>แพลตฟอร์มมุ่งเชื่อมโยงองค์ความรู้ด้านจิตวิทยาการเรียนรู้ พัฒนาการเด็ก Universal Design for Learning, Differentiated Instruction, Inclusive Education และ Assessment for Learning เข้ากับตัวอย่าง เครื่องมือ และคำถามที่ครูนำไปใช้ได้ทันที</p><div className="purpose-grid"><div><span>01</span><strong>พัฒนาความรู้</strong><p>เข้าถึงแนวคิดสำคัญด้วยภาษาที่ชัดเจนและมีหลักฐานรองรับ</p></div><div><span>02</span><strong>สร้างความเข้าใจ</strong><p>วิเคราะห์ผู้เรียนโดยไม่รีบตัดสิน วินิจฉัย หรือติดป้าย</p></div><div><span>03</span><strong>หล่อหลอมทัศนคติ</strong><p>ส่งเสริม Empathy, Growth Mindset และ Inclusive Mindset</p></div><div><span>04</span><strong>พัฒนาทักษะครู</strong><p>ออกแบบกิจกรรม ประเมิน และช่วยเหลือผู้เรียนจากหลักฐาน</p></div></div></article><aside className="creator-card"><span className="creator-monogram" aria-hidden="true">BP</span><span className="section-kicker left">ผู้จัดทำ</span><h2>Boorapatis Ploysuwan</h2><p className="creator-role">ผู้วิจัยอิสระ</p><p>สนใจการออกแบบระบบความรู้ เทคโนโลยีการศึกษา และการสร้างเครื่องมือที่ช่วยให้ครูเข้าใจผู้เรียนได้ลึกขึ้นและลงมือช่วยเหลือได้อย่างเป็นรูปธรรม</p><a className="contact-button" href="mailto:burapatis@gmail.com">✉ burapatis@gmail.com</a></aside></section><section className="vision-band"><div><span>VISION</span><h2>ครูทุกคนมองเห็น เข้าใจ และตอบสนองต่อความเป็นเอกลักษณ์ของผู้เรียนได้</h2></div><div><span>MISSION</span><h2>เปลี่ยนองค์ความรู้ให้เป็นการตัดสินใจเล็ก ๆ ที่ทำให้ห้องเรียนเข้าถึงและท้าทายสำหรับทุกคน</h2></div></section><section className="subpage-section values-section"><span className="section-kicker left">แนวคิดที่ยึดถือ</span><div className="values-grid"><div><strong>Understand Every Learner</strong><p>เริ่มต้นจากการฟัง สังเกต และทำความเข้าใจ</p></div><div><strong>Teach for Differences</strong><p>ออกแบบความยืดหยุ่นโดยไม่ลดความคาดหวัง</p></div><div><strong>Every Child Can Learn</strong><p>เชื่อในศักยภาพและการเติบโตของผู้เรียนทุกคน</p></div></div></section></SubPage>;
}
