"use client";
import { useState } from "react";
const prompts=[
  {tag:"วิเคราะห์ผู้เรียน",title:"แยกหลักฐานออกจากสมมติฐาน",text:"ช่วยวิเคราะห์ข้อมูลการสังเกตต่อไปนี้ โดยแยกเป็น 1) ข้อเท็จจริงที่สังเกตได้ 2) จุดแข็ง 3) สมมติฐานที่ยังต้องตรวจสอบ 4) คำถามที่ควรถามผู้เรียน และ 5) วิธีช่วยเหลือที่ทดลองได้ 3 วิธี หลีกเลี่ยงการวินิจฉัยหรือติดป้าย: [ข้อมูลที่ไม่ระบุตัวตน]"},
  {tag:"ออกแบบการเรียนรู้",title:"วางแผนด้วย UDL",text:"ช่วยออกแบบบทเรียนเรื่อง [หัวข้อ] สำหรับ [ระดับชั้น] เป้าหมายคือ [ผลลัพธ์] โดยเสนอหลายวิธีในการมีส่วนร่วม รับข้อมูล และแสดงความเข้าใจ ใช้เกณฑ์คุณภาพเดียวกัน และระบุอุปสรรคที่แต่ละทางเลือกช่วยลด"},
  {tag:"สร้างกิจกรรม",title:"Differentiation ที่ไม่ลดความคาดหวัง",text:"สร้างกิจกรรม [ระยะเวลา] เพื่อเป้าหมาย [เป้าหมาย] โดยปรับระดับการพยุงตามความพร้อม 3 ระดับ ทุกกลุ่มทำงานที่มีคุณค่าและใช้เกณฑ์สำเร็จเดียวกัน พร้อมบอกวิธีเปลี่ยนกลุ่มจากหลักฐานล่าสุด"},
  {tag:"ประเมินผล",title:"Exit Ticket ที่เห็นการคิด",text:"สร้าง Exit Ticket 3 ข้อสำหรับเป้าหมาย [เป้าหมาย] ให้มีทั้งการอธิบายเหตุผล การใช้หลักฐาน และการประเมินความมั่นใจ พร้อมแนวทางแปลผลเพื่อเลือกกิจกรรมคาบถัดไป"},
  {tag:"สะท้อนผลการสอน",title:"จากสิ่งที่เกิดขึ้นสู่ก้าวถัดไป",text:"ช่วยนำการสะท้อนผลจากข้อมูล [หลักฐานหลังสอน] โดยถามทีละข้อเกี่ยวกับ 1) ใครมี/ไม่มีส่วนร่วม 2) อุปสรรคจากการออกแบบ 3) สิ่งที่ได้ผลและหลักฐาน 4) สมมติฐานทางเลือก และ 5) การเปลี่ยนแปลงเล็กที่สุดที่ควรทดลองต่อ"},
];
export default function PromptsClient(){const[copied,setCopied]=useState<number|null>(null);const copy=async(index:number,text:string)=>{await navigator.clipboard.writeText(text);setCopied(index);setTimeout(()=>setCopied(null),1800)};return <section className="subpage-section prompts-page" id="top"><div className="prompt-stack">{prompts.map((prompt,index)=><article key={prompt.tag}><div><span className="case-tag">{prompt.tag}</span><h2>{prompt.title}</h2></div><p>{prompt.text}</p><button onClick={()=>copy(index,prompt.text)}>{copied===index?"คัดลอกแล้ว ✓":"คัดลอก Prompt"}</button></article>)}</div><aside className="prompt-safety"><h2>ก่อนส่ง Prompt</h2><ul><li>ใช้รหัสแทนชื่อจริง</li><li>ให้ AI แยกข้อเท็จจริงกับสมมติฐาน</li><li>ขอทางเลือกมากกว่าคำตอบเดียว</li><li>ตรวจคำแนะนำกับบริบทและหลักฐานจริง</li></ul><a href="/principles#responsible-ai">หลักการใช้ AI อย่างรับผิดชอบ →</a></aside></section>}
