"use client";

import { useEffect, useState } from "react";

type Note = { id: string; date: string; context: string; observation: string; learnerVoice: string; nextStep: string };
const empty = { date:"", context:"", observation:"", learnerVoice:"", nextStep:"" };
const interviewQuestions = ["วันนี้ช่วงไหนที่รู้สึกว่าเรียนรู้ได้ดีที่สุด เพราะอะไร?","ช่วงไหนที่รู้สึกติดขัด และตอนนั้นต้องการความช่วยเหลือแบบใด?","มีวิธีทำงานหรืออธิบายแบบไหนที่ช่วยให้แสดงสิ่งที่รู้ได้ดี?","เรื่องนี้เชื่อมกับสิ่งที่สนใจหรือประสบการณ์ของคุณอย่างไร?","ครั้งหน้ามีอะไรหนึ่งอย่างที่ครูเปลี่ยนแล้วน่าจะช่วย?","คุณอยากตั้งเป้าหมายเล็ก ๆ อะไรสำหรับคาบถัดไป?"];
const rubric = [
  ["1 · หลักฐานเริ่มต้น","มีเหตุการณ์เดียวหรือมีการตีความปะปนสูง","เก็บข้อมูลเพิ่มและเขียนเฉพาะสิ่งที่เห็น/ได้ยิน"],
  ["2 · เห็นรูปแบบบางส่วน","มีมากกว่าหนึ่งเหตุการณ์ แต่ยังอยู่ในบริบทคล้ายกัน","ลองสังเกตต่างวิชา เวลา หรือรูปแบบงาน"],
  ["3 · หลักฐานรอบด้าน","มีหลายบริบท พร้อมเสียงผู้เรียนและจุดแข็ง","ตั้งสมมติฐานหลายทางและทดลองก้าวเล็ก"],
  ["4 · ใช้ตัดสินใจได้","หลักฐานเชื่อมกับการทดลอง ผลที่ติดตาม และการทบทวน","ปรับ ลด หรือยุติการช่วยเหลือตามข้อมูลล่าสุด"],
];

export default function ToolkitExtras(){
  const [draft,setDraft]=useState(empty); const [notes,setNotes]=useState<Note[]>([]); const [message,setMessage]=useState("");
  useEffect(()=>{queueMicrotask(()=>{const raw=localStorage.getItem("learnerlens-observation-notes");if(raw)try{setNotes(JSON.parse(raw));}catch{localStorage.removeItem("learnerlens-observation-notes")}})},[]);
  const update=(key:keyof typeof empty,value:string)=>setDraft(current=>({...current,[key]:value}));
  const add=()=>{if(!draft.observation.trim()||!draft.context.trim()){setMessage("กรุณากรอกบริบทและสิ่งที่สังเกตได้");return}const next=[{...draft,id:crypto.randomUUID(),date:draft.date||new Date().toISOString().slice(0,10)},...notes];setNotes(next);localStorage.setItem("learnerlens-observation-notes",JSON.stringify(next));setDraft(empty);setMessage("บันทึกหลักฐานแล้ว ✓")};
  const remove=(id:string)=>{const next=notes.filter(note=>note.id!==id);setNotes(next);localStorage.setItem("learnerlens-observation-notes",JSON.stringify(next))};
  return <div className="toolkit-extra-stack"><section className="observation-tool" id="observation-log"><header><div><span className="section-kicker left">OBSERVATION LOG</span><h2>บันทึกสิ่งที่เกิดขึ้น ก่อนตีความ</h2><p>ใช้รหัสแทนชื่อจริง บันทึกพฤติกรรมและบริบทที่ตรวจสอบได้ แล้วแยกเสียงผู้เรียนกับก้าวถัดไปให้ชัด</p></div><strong>{notes.length} บันทึก</strong></header><div className="observation-layout"><form onSubmit={event=>{event.preventDefault();add()}}><div className="form-grid"><label>วันที่<input type="date" value={draft.date} onChange={e=>update("date",e.target.value)}/></label><label>บริบท/กิจกรรม<input value={draft.context} onChange={e=>update("context",e.target.value)} placeholder="เช่น คณิตศาสตร์ งานคู่ 20 นาที"/></label></div><label>สิ่งที่สังเกตได้<textarea value={draft.observation} onChange={e=>update("observation",e.target.value)} placeholder="เขียนสิ่งที่เห็นหรือได้ยิน หลีกเลี่ยงคำว่า ขี้เกียจ ไม่สนใจ..."/></label><label>เสียงหรือมุมมองของผู้เรียน<textarea value={draft.learnerVoice} onChange={e=>update("learnerVoice",e.target.value)} placeholder="คำพูดหรือใจความที่ผู้เรียนสื่อ"/></label><label>ก้าวถัดไปที่จะทดลอง<textarea value={draft.nextStep} onChange={e=>update("nextStep",e.target.value)} placeholder="การเปลี่ยนแปลงเล็ก ๆ ที่จะทดลองและติดตาม"/></label><div className="builder-actions"><button className="primary-button" type="submit">เพิ่มบันทึก</button><span className="form-message" role="status">{message}</span></div></form><div className="observation-list">{notes.length?notes.map(note=><article key={note.id}><header><strong>{note.context}</strong><time>{note.date}</time></header><p><b>สังเกต:</b> {note.observation}</p>{note.learnerVoice&&<p><b>เสียงผู้เรียน:</b> {note.learnerVoice}</p>}{note.nextStep&&<p><b>ก้าวถัดไป:</b> {note.nextStep}</p>}<button type="button" onClick={()=>remove(note.id)}>ลบบันทึกนี้</button></article>):<div className="empty-notes"><span>▤</span><strong>ยังไม่มีบันทึก</strong><p>เริ่มจากเหตุการณ์สั้น ๆ หนึ่งเหตุการณ์ แล้วกลับมาดูรูปแบบเมื่อมีข้อมูลมากขึ้น</p></div>}</div></div></section><section className="interview-guide" id="interview-guide"><div><span className="section-kicker left">INTERVIEW GUIDE</span><h2>คำถามที่ช่วยให้ได้ยินเสียงผู้เรียน</h2><p>เลือกใช้ 2–3 ข้อในบทสนทนาสั้น ๆ ไม่จำเป็นต้องถามครบ และควรสะท้อนสิ่งที่ได้ยินกลับไปให้ผู้เรียนตรวจสอบ</p></div><ol>{interviewQuestions.map((question,index)=><li key={question}><span>{index+1}</span>{question}</li>)}</ol></section><section className="evidence-rubric" id="evidence-rubric"><span className="section-kicker left">EVIDENCE RUBRIC</span><h2>หลักฐานของเราพร้อมใช้ตัดสินใจแค่ไหน?</h2><div>{rubric.map(row=><article key={row[0]}><h3>{row[0]}</h3><p>{row[1]}</p><strong>ก้าวถัดไป</strong><span>{row[2]}</span></article>)}</div></section></div>;
}
